language: cpp
compiler:
  - gcc
  - clang
env:
  - STATIC=ON
  - STATIC=OFF
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-multilib g++-multilib python-pip doxygen
  - sudo pip install ply cidl
  - wget http://www.cmake.org/files/v2.8/cmake-2.8.12.2-Linux-i386.sh
  - sudo sh cmake-2.8.12.2-Linux-i386.sh --exclude-subdir --prefix=/usr
  - git clone https://github.com/Zeex/samp-plugin-sdk.git sdk
  - export SAMP_SDK_DIR=$PWD/sdk
before_script:
  - cmake . -DCMAKE_C_COMPILER=${CC}
            -DCMAKE_CXX_COMPILER=${CXX}
            -DSAMPGDK_STATIC=${STATIC}
            -DSAMPGDK_BUILD_PLUGINS=ON
            -DSAMPGDK_BUILD_AMALGAMATION=ON
script:
  - make
  - make package
