version: '{build}'

configuration:
  - RelWithDebInfo

environment:
  SAMP_SDK_ROOT: sdk

  matrix:
  - STATIC: ON
  - STATIC: OFF

install:
  - choco install -y doxygen.install
  - set PATH=%PATH%;C:\Python27\Scripts
  - pip install ply
  - git clone https://github.com/Zeex/samp-plugin-sdk.git sdk

before_build:
  - mkdir build && cd build
  - cmake .. -G "Visual Studio 10 2010"
             -DSAMPGDK_STATIC=%STATIC%
             -DSAMPGDK_BUILD_PLUGINS=ON
             -DSAMPGDK_BUILD_AMALGAMATION=ON

build_script:
  - cmake --build . --config %CONFIGURATION%
  - cmake --build . --config %CONFIGURATION% --target package

artifacts:
  - path: build/sampgdk-*-amalgamation.zip
    name: Amalgamation (concatenated source code)
