version: '{build}'

configuration:
  - RelWithDebInfo

environment:
  SAMP_SDK_ROOT: sdk

  matrix:
  - STATIC: ON
  - STATIC: OFF

install:
  - choco install -y doxygen.install

  - set PATH=%PATH%;C:\Python27\Scripts
  - pip install ply
  - pip install cidl

  - git clone https://github.com/Zeex/samp-plugin-sdk.git sdk

before_build:
  - cmake . -G "Visual Studio 10 2010"
            -DSAMPGDK_STATIC=%STATIC%
            -DSAMPGDK_BUILD_PLUGINS=ON
            -DSAMPGDK_BUILD_AMALGAMATION=ON

build_script:
  - cmake --build . --config %CONFIGURATION%
  - cmake --build . --config %CONFIGURATION% --target package

artifacts:
  - path: sampgdk-*-win32.zip
    name: Binaries

  - path: sampgdk-*-win32-static.zip
    name: Binaries (static)

  - path: sampgdk-*-amalgamation.zip
    name: Amalgamation
